### ISSUE TITLE
Such a bad schematic

### ISSUE THREAD

**Issue by bangcht** [hiepph/R3#1]
@hiepph Please export your schematic from a circuit design software to provide a professional image, love you!

**Comment by hiepph** [comment]
It is actually exported from `fritzing` but it is bad, really ><

**Comment by bangcht** [comment]
Have you tried [Altium](http://www.altium.com/altium-designer/overview) yet?

**Comment by hiepph** [comment]
No, does it support linux. Maybe for my #R4 :D
